export const datos = [
  {
    id: 1,
    column: 4,
    puzzle: [
      "L",
      "U",
      "N",
      "A",
      "E",
      "B",
      "U",
      "N",
      "U",
      "G",
      "I",
      "I",
      "A",
      "I",
      "R",
      "E",
    ],
    words: [
      { id: 1, word: "LUNA", answer: [1, 2, 3, 4], strike: false },
      { id: 2, word: "NUBE", answer: [5, 6, 7, 8], strike: false },
      { id: 3, word: "AIRE", answer: [13, 14, 15, 16], strike: false },
      { id: 4, word: "AGUA", answer: [4, 7, 10, 13], strike: false },
    ],
    className: "grid grid-cols-4",
    position: [1, 2, 3, 4, 5, 6, 7, 8, 10, 13, 14, 15, 16],
    isSelected: false,
  },
  {
    id: 2,
    column: 5,
    puzzle: [
      "O",
      "T",
      "A",
      "P",
      "M",
      "K",
      "R",
      "I",
      "R",
      "O",
      "N",
      "A",
      "R",
      "K",
      "N",
      "O",
      "T",
      "Y",
      "E",
      "O",
      "P",
      "O",
      "N",
      "I",
      "P",
    ],

    words: [
      { id: 1, word: "PONI", answer: [21, 22, 23, 24], strike: false },
      { id: 2, word: "PATO", answer: [1, 2, 3, 4], strike: false },
      { id: 3, word: "YAK", answer: [6, 12, 18], strike: false },
      { id: 4, word: "MONO", answer: [5, 10, 15, 20], strike: false },
      { id: 5, word: "PERRO", answer: [1, 7, , 13, 19, 25], strike: false },
    ],
    className: "grid grid-cols-5",
    position: [
      1, 2, 3, 4, 5, 6, 7, 10, 12, 13, 15, 18, 19, 20, 21, 22, 23, 24, 25,
    ],
    isSelected: false,
  },
  {
    id: 3,
    column: 6,
    puzzle: [
      "A",
      "O",
      "L",
      "C",
      "G",
      "A",
      "G",
      "N",
      "A",
      "R",
      "R",
      "O",
      "A",
      "L",
      "E",
      "N",
      "A",
      "C",
      "A",
      "E",
      "T",
      "R",
      "N",
      "R",
      "O",
      "L",
      "I",
      "V",
      "A",
      "E",
      "C",
      "O",
      "R",
      "A",
      "L",
      "C",
    ],
    words: [
      {
        id: 1,
        word: "CANELA",
        answer: [13, 14, 15, 16, 17, 18],
        strike: false,
      },
      { id: 2, word: "OLIVA", answer: [25, 26, 27, 28, 29], strike: false },
      { id: 3, word: "TEAL", answer: [3, 9, 15, 21], strike: false },
      { id: 4, word: "OCRE", answer: [12, 18, 24, 30], strike: false },
      { id: 5, word: "ARENA", answer: [1, 8, 15, 22, 29], strike: false },
      { id: 6, word: "GRANA", answer: [5, 11, 17, 23, 29], strike: false },
      { id: 7, word: "CORAL", answer: [31, 32, 33, 34, 35], strike: false },
    ],

    className: "grid grid-cols-6",

    position: [
      1, 3, 5, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27,
      28, 29, 30, 31, 32, 33, 34, 35,
    ],
    isSelected: false,
  },

  {
    id: 4,
    column: 7,
    puzzle: [
      "L",
      "Z",
      "Ñ",
      "T",
      "N",
      "P",
      "R",
      "A",
      "I",
      "C",
      "I",
      "L",
      "O",
      "P",
      "C",
      "R",
      "Ñ",
      "U",
      "D",
      "E",
      "J",
      "T",
      "T",
      "M",
      "A",
      "U",
      "T",
      "U",
      "O",
      "C",
      "Z",
      "U",
      "B",
      "A",
      "E",
      "R",
      "A",
      "C",
      "U",
      "Z",
      "L",
      "Z",
      "C",
      "A",
      "J",
      "N",
      "O",
      "M",
      "A",
    ],
    words: [
      {
        id: 1,
        word: "MONJA",
        answer: [48, 47, 46, 45, 44],
        strike: false,
      },
      { id: 2, word: "ACTOR", answer: [8, 15, 22, 29, 36], strike: false },
      {
        id: 3,
        word: "ALBAÑIL",
        answer: [1, 9, 17, 25, 33, 41, 49],
        strike: false,
      },
      {
        id: 4,
        word: "CAZADOR",
        answer: [7, 13, 19, 25, 31, 37, 43],
        strike: false,
      },
      { id: 5, word: "JUEZ", answer: [21, 28, 35, 42], strike: false },
      { id: 6, word: "POETA", answer: [6, 13, 20, 27, 34], strike: false },
      {
        id: 7,
        word: "POLICIA",
        answer: [8, 9, 10, 11, 12, 13, 14],
        strike: false,
      },
      { id: 8, word: "ACTRIZ", answer: [2, 9, 16, 23, 30, 37], strike: false },
    ],

    className: "grid grid-cols-7 ",
    position: [
      1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25,
      27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 46, 47, 48,
      49,
    ],
    isSelected: false,
  },
];
