export const datos = [
  {
    id: 1,
    column: 4,
    puzzle: [
      { letter: "L", id: 1, isSelected: false },
      { letter: "U", id: 2, isSelected: false },
      { letter: "N", id: 3, isSelected: false },
      { letter: "A", id: 4, isSelected: false },
      { letter: "E", id: 5, isSelected: false },
      { letter: "B", id: 6, isSelected: false },
      { letter: "U", id: 7, isSelected: false },
      { letter: "N", id: 8, isSelected: false },
      { letter: "U", id: 9, isSelected: false },
      { letter: "G", id: 10, isSelected: false },
      { letter: "I", id: 11, isSelected: false },
      { letter: "I", id: 12, isSelected: false },
      { letter: "A", id: 13, isSelected: false },
      { letter: "I", id: 14, isSelected: false },
      { letter: "R", id: 15, isSelected: false },
      { letter: "E", id: 16, isSelected: false },
    ],
    words: [
      { id: 1, word: "LUNA", answer: [1, 2, 3, 4], strike: false },
      { id: 2, word: "NUBE", answer: [5, 6, 7, 8], strike: false },
      { id: 3, word: "AIRE", answer: [13, 14, 15, 16], strike: false },
      { id: 4, word: "AGUA", answer: [4, 7, 10, 13], strike: false },
    ],
    className: "grid grid-cols-4",

    background:
      "bg-gradient-to-b from-red-500 to-orange-400 min-h-screen flex items-center justify-center",
    position: [1, 2, 3, 4, 5, 6, 7, 8, 10, 13, 14, 15, 16],
    isSelected: false,
  },
  {
    id: 2,
    column: 5,
    puzzle: [
      { letter: "O", id: 1, isSelected: false },
      { letter: "T", id: 2, isSelected: false },
      { letter: "A", id: 3, isSelected: false },
      { letter: "P", id: 4, isSelected: false },
      { letter: "M", id: 5, isSelected: false },
      { letter: "K", id: 6, isSelected: false },
      { letter: "R", id: 7, isSelected: false },
      { letter: "I", id: 8, isSelected: false },
      { letter: "R", id: 9, isSelected: false },
      { letter: "O", id: 10, isSelected: false },
      { letter: "N", id: 11, isSelected: false },
      { letter: "A", id: 12, isSelected: false },
      { letter: "R", id: 13, isSelected: false },
      { letter: "K", id: 14, isSelected: false },
      { letter: "N", id: 15, isSelected: false },
      { letter: "O", id: 16, isSelected: false },
      { letter: "T", id: 17, isSelected: false },
      { letter: "Y", id: 18, isSelected: false },
      { letter: "E", id: 19, isSelected: false },
      { letter: "O", id: 20, isSelected: false },
      { letter: "P", id: 21, isSelected: false },
      { letter: "O", id: 22, isSelected: false },
      { letter: "N", id: 23, isSelected: false },
      { letter: "I", id: 24, isSelected: false },
      { letter: "P", id: 25, isSelected: false },
    ],

    words: [
      { id: 1, word: "PONI", answer: [21, 22, 23, 24], strike: false },
      { id: 2, word: "PATO", answer: [1, 2, 3, 4], strike: false },
      { id: 3, word: "YAK", answer: [6, 12, 18], strike: false },
      { id: 4, word: "MONO", answer: [5, 10, 15, 20], strike: false },
      { id: 5, word: "PERRO", answer: [1, 7, , 13, 19, 25], strike: false },
    ],
    className: "grid grid-cols-5",
    background:
      "bg-gradient-to-r from-yellow-400 to-purple-400 min-h-screen flex items-center justify-center",

    position: [
      1, 2, 3, 4, 5, 6, 7, 10, 12, 13, 15, 18, 19, 20, 21, 22, 23, 24, 25,
    ],
    isSelected: false,
  },
  {
    id: 3,
    column: 6,
    puzzle: [
      { letter: "A", id: 1, isSelected: false },
      { letter: "O", id: 2, isSelected: false },
      { letter: "L", id: 3, isSelected: false },
      { letter: "C", id: 4, isSelected: false },
      { letter: "G", id: 5, isSelected: false },
      { letter: "A", id: 6, isSelected: false },
      { letter: "G", id: 7, isSelected: false },
      { letter: "N", id: 8, isSelected: false },
      { letter: "A", id: 9, isSelected: false },
      { letter: "R", id: 10, isSelected: false },
      { letter: "R", id: 11, isSelected: false },
      { letter: "O", id: 12, isSelected: false },
      { letter: "A", id: 13, isSelected: false },
      { letter: "L", id: 14, isSelected: false },
      { letter: "E", id: 15, isSelected: false },
      { letter: "N", id: 16, isSelected: false },
      { letter: "A", id: 17, isSelected: false },
      { letter: "C", id: 18, isSelected: false },
      { letter: "A", id: 19, isSelected: false },
      { letter: "E", id: 20, isSelected: false },
      { letter: "T", id: 21, isSelected: false },
      { letter: "R", id: 22, isSelected: false },
      { letter: "N", id: 23, isSelected: false },
      { letter: "R", id: 24, isSelected: false },
      { letter: "O", id: 25, isSelected: false },
      { letter: "L", id: 26, isSelected: false },
      { letter: "I", id: 27, isSelected: false },
      { letter: "V", id: 28, isSelected: false },
      { letter: "A", id: 29, isSelected: false },
      { letter: "E", id: 30, isSelected: false },
      { letter: "C", id: 31, isSelected: false },
      { letter: "O", id: 32, isSelected: false },
      { letter: "R", id: 33, isSelected: false },
      { letter: "A", id: 34, isSelected: false },
      { letter: "L", id: 35, isSelected: false },
      { letter: "C", id: 36, isSelected: false },
    ],
    words: [
      {
        id: 1,
        word: "CANELA",
        answer: [13, 14, 15, 16, 17, 18],
        strike: false,
      },
      { id: 2, word: "OLIVA", answer: [25, 26, 27, 28, 29], strike: false },
      { id: 3, word: "TEAL", answer: [3, 9, 15, 21], strike: false },
      { id: 4, word: "OCRE", answer: [12, 18, 24, 30], strike: false },
      { id: 5, word: "ARENA", answer: [1, 8, 15, 22, 29], strike: false },
      { id: 6, word: "GRANA", answer: [5, 11, 17, 23, 29], strike: false },
      { id: 7, word: "CORAL", answer: [31, 32, 33, 34, 35], strike: false },
    ],

    className: "grid grid-cols-6",
    background:
      "bg-gradient-radial from-blue-200 via-blue-500 to-blue-800 min-h-screen flex items-center justify-center",

    position: [
      1, 3, 5, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, 24, 25, 26, 27,
      28, 29, 30, 31, 32, 33, 34, 35,
    ],
    isSelected: false,
  },

  {
    id: 4,
    column: 7,
    background:
      "bg-gradient-to-b from-pink-500 to-violet-500 min-h-screen flex items-center justify-center",
    puzzle: [
      { letter: "L", id: 1, isSelected: false },
      { letter: "Z", id: 2, isSelected: false },
      { letter: "Ñ", id: 3, isSelected: false },
      { letter: "T", id: 4, isSelected: false },
      { letter: "N", id: 5, isSelected: false },
      { letter: "P", id: 6, isSelected: false },
      { letter: "R", id: 7, isSelected: false },
      { letter: "A", id: 8, isSelected: false },
      { letter: "I", id: 9, isSelected: false },
      { letter: "C", id: 10, isSelected: false },
      { letter: "I", id: 11, isSelected: false },
      { letter: "L", id: 12, isSelected: false },
      { letter: "O", id: 13, isSelected: false },
      { letter: "P", id: 14, isSelected: false },
      { letter: "C", id: 15, isSelected: false },
      { letter: "R", id: 16, isSelected: false },
      { letter: "Ñ", id: 17, isSelected: false },
      { letter: "U", id: 18, isSelected: false },
      { letter: "D", id: 19, isSelected: false },
      { letter: "E", id: 20, isSelected: false },
      { letter: "J", id: 21, isSelected: false },
      { letter: "T", id: 22, isSelected: false },
      { letter: "T", id: 23, isSelected: false },
      { letter: "M", id: 24, isSelected: false },
      { letter: "A", id: 25, isSelected: false },
      { letter: "U", id: 26, isSelected: false },
      { letter: "T", id: 27, isSelected: false },
      { letter: "U", id: 28, isSelected: false },
      { letter: "O", id: 29, isSelected: false },
      { letter: "C", id: 30, isSelected: false },
      { letter: "Z", id: 31, isSelected: false },
      { letter: "U", id: 32, isSelected: false },
      { letter: "B", id: 33, isSelected: false },
      { letter: "A", id: 34, isSelected: false },
      { letter: "E", id: 35, isSelected: false },
      { letter: "R", id: 36, isSelected: false },
      { letter: "A", id: 37, isSelected: false },
      { letter: "C", id: 38, isSelected: false },
      { letter: "U", id: 39, isSelected: false },
      { letter: "Z", id: 40, isSelected: false },
      { letter: "L", id: 41, isSelected: false },
      { letter: "Z", id: 42, isSelected: false },
      { letter: "C", id: 43, isSelected: false },
      { letter: "A", id: 44, isSelected: false },
      { letter: "J", id: 45, isSelected: false },
      { letter: "N", id: 46, isSelected: false },
      { letter: "O", id: 47, isSelected: false },
      { letter: "M", id: 48, isSelected: false },
      { letter: "A", id: 49, isSelected: false },
    ],
    words: [
      {
        id: 1,
        word: "MONJA",
        answer: [48, 47, 46, 45, 44],
        strike: false,
      },
      { id: 2, word: "ACTOR", answer: [8, 15, 22, 29, 36], strike: false },
      {
        id: 3,
        word: "ALBAÑIL",
        answer: [1, 9, 17, 25, 33, 41, 49],
        strike: false,
      },
      {
        id: 4,
        word: "CAZADOR",
        answer: [7, 13, 19, 25, 31, 37, 43],
        strike: false,
      },
      { id: 5, word: "JUEZ", answer: [21, 28, 35, 42], strike: false },
      { id: 6, word: "POETA", answer: [6, 13, 20, 27, 34], strike: false },
      {
        id: 7,
        word: "POLICIA",
        answer: [8, 9, 10, 11, 12, 13, 14],
        strike: false,
      },
      { id: 8, word: "ACTRIZ", answer: [2, 9, 16, 23, 30, 37], strike: false },
    ],

    className: "grid grid-cols-7 ",
    position: [
      1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25,
      27, 28, 29, 30, 31, 33, 34, 35, 36, 37, 41, 42, 43, 44, 45, 46, 47, 48,
      49,
    ],
    isSelected: false,
  },
];
